package trabajo_final_Formularios.filtro;

import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import trabajo_final.clases.DtoAcuerdoMarco;
import trabajo_final.clases.DtoFecha;
import trabajo_final.clases.Entidad;
import trabajo_final.clases.Proveedor;
import trabajo_final.datos.Datos;
import trabajo_final.estructura.Pila;
import trabajo_final.estructura.PilaEntidad;
import trabajo_final.modelo.ModeloEntidad;
import trabajo_final.util.EntidadNodoInterfaceImpl;
import trabajo_final_Formularios.FormBusqueda;
import trabajo_final_Formularios.FormEstEntidadProveedor;


/**
 *
 * @author author Flaven
 */
public class FormFiltro extends javax.swing.JFrame {

    private static int tipo;
    private static FormFiltro form;
    Datos objDatos= new Datos();
    /**
     * Creates new form FormPrincipal
     */
    private FormFiltro() {
        initComponents();        
      
    }
    
    public static FormFiltro crearVentana(int tipo) {
        if (form == null) {
            form = new FormFiltro();
            FormFiltro.tipo=tipo;
        }
        FormFiltro.tipo=tipo;
        form.setVisible(true);
        return form;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        BG = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblObjeto = new javax.swing.JTable();
        btnFiltro = new javax.swing.JButton();
        chkTodo = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        BG.setBackground(new java.awt.Color(255, 255, 255));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 36)); // NOI18N
        jLabel2.setText("Filtro");
        BG.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        BG.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        BG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 60));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        BG.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 100, -1));

        tblObjeto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Filtro", "RUC", "ENTIDAD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblObjeto.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblObjeto);
        tblObjeto.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tblObjeto.getColumnModel().getColumnCount() > 0) {
            tblObjeto.getColumnModel().getColumn(0).setMaxWidth(50);
            tblObjeto.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        BG.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 440, 250));

        btnFiltro.setText("Filtrar");
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });
        BG.add(btnFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 100, -1));

        chkTodo.setText("Seleccionar todo");
        BG.add(chkTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
                
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
        
        switch(tipo){
            case 0:// ENTIDAD
                FormBusqueda.setPilaEntidadFiltro(new PilaEntidad());
                if(chkTodo.isSelected()) {
                    for (int count = 0; count < tblObjeto.getModel().getRowCount(); count++){
                        Entidad entidad =Datos.getPilaEntidad()[count];                                                
                        FormBusqueda.getPilaEntidadFiltro().Apilar(entidad);                        
                    }
                }else{
                    for (int count = 0; count < tblObjeto.getModel().getRowCount(); count++){
                        Boolean bfiltro=(Boolean)tblObjeto.getModel().getValueAt(count, 0);
                        if(bfiltro){
                            Entidad entidad =Datos.getPilaEntidad()[count];                                                
                            FormBusqueda.getPilaEntidadFiltro().Apilar(entidad);                        
                        }
                    }
                }
                this.dispose();
                break;
            case 1:// PROVEEDOR
                FormBusqueda.setPilaProveedorFiltro(new Pila());
                if(chkTodo.isSelected()) {
                    for (int count = 0; count < tblObjeto.getModel().getRowCount(); count++){
                        Proveedor proveedor =Datos.getPilaProveedor()[count];                                                
                        FormBusqueda.getPilaProveedorFiltro().Apilar(proveedor);
                    }
                }else{
                    for (int count = 0; count < tblObjeto.getModel().getRowCount(); count++){
                        Boolean bfiltro=(Boolean)tblObjeto.getModel().getValueAt(count, 0);
                        if(bfiltro){
                            Proveedor proveedor =Datos.getPilaProveedor()[count];                                                
                            FormBusqueda.getPilaProveedorFiltro().Apilar(proveedor);                        
                        }
                    }                    
                }
                this.dispose();
                break;
            case 2:// FORMALIZACION
                FormBusqueda.setPilaFechasFiltro(new Pila());
                if(chkTodo.isSelected()) {
                    for (int count = 0; count < tblObjeto.getModel().getRowCount(); count++){
                        DtoFecha fecha =Datos.getPilaFechas()[count];                                                
                        FormBusqueda.getPilaFechasFiltro().Apilar(fecha);
                    }
                }else{
                    for (int count = 0; count < tblObjeto.getModel().getRowCount(); count++){
                        Boolean bfiltro=(Boolean)tblObjeto.getModel().getValueAt(count, 0);
                        if(bfiltro){
                            DtoFecha fecha =Datos.getPilaFechas()[count];                                                
                            FormBusqueda.getPilaFechasFiltro().Apilar(fecha);                        
                        }
                    }
                }
                this.dispose();
                break;
            case 3:// ACUERDO
                if(chkTodo.isSelected()) {
                    for (int count = 0; count < tblObjeto.getModel().getRowCount(); count++){
                        DtoAcuerdoMarco acuerdo =Datos.getPilaAcuerdoMarco()[count];                                                
                        FormBusqueda.getPilaAcuerdoFiltro().Apilar(acuerdo);  
                    }
                }else{
                    FormBusqueda.setPilaAcuerdoFiltro(new Pila());
                    for (int count = 0; count < tblObjeto.getModel().getRowCount(); count++){
                        Boolean bfiltro=(Boolean)tblObjeto.getModel().getValueAt(count, 0);
                        if(bfiltro){
                            DtoAcuerdoMarco acuerdo =Datos.getPilaAcuerdoMarco()[count];                                                
                            FormBusqueda.getPilaAcuerdoFiltro().Apilar(acuerdo);                        
                        }
                    }
                }
                this.dispose();
                break;
            case 4:// ENTIDAD ESTADISTICA 1
                FormEstEntidadProveedor.setPilaEntidadFiltro(new PilaEntidad());
                if(chkTodo.isSelected()) {
                    for (int count = 0; count < tblObjeto.getModel().getRowCount(); count++){
                        Entidad entidad =Datos.getPilaEntidad()[count];                                                
                        FormEstEntidadProveedor.getPilaEntidadFiltro().Apilar(entidad);                        
                    }
                }else{
                    for (int count = 0; count < tblObjeto.getModel().getRowCount(); count++){
                        Boolean bfiltro=(Boolean)tblObjeto.getModel().getValueAt(count, 0);
                        if(bfiltro){
                            Entidad entidad =Datos.getPilaEntidad()[count];                                                
                            FormEstEntidadProveedor.getPilaEntidadFiltro().Apilar(entidad);                        
                        }
                    }
                }
                this.dispose();
                break;
            case 5:// PROVEEDOR ESTADISTICA 1
                FormEstEntidadProveedor.setPilaProveedorFiltro(new Pila());
                if(chkTodo.isSelected()) {
                    for (int count = 0; count < tblObjeto.getModel().getRowCount(); count++){
                        Proveedor proveedor =Datos.getPilaProveedor()[count];                                                
                        FormEstEntidadProveedor.getPilaProveedorFiltro().Apilar(proveedor);
                    }
                }else{
                    for (int count = 0; count < tblObjeto.getModel().getRowCount(); count++){
                        Boolean bfiltro=(Boolean)tblObjeto.getModel().getValueAt(count, 0);
                        if(bfiltro){
                            Proveedor proveedor =Datos.getPilaProveedor()[count];                                                
                            FormEstEntidadProveedor.getPilaProveedorFiltro().Apilar(proveedor);                        
                        }
                    }                    
                }
                this.dispose();
                break;
            default:break;
        }  
        
    }//GEN-LAST:event_btnFiltroActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here
        Object[] columnas =null;
        Object[][]datos=null;
        switch(tipo){
            case 0:// ENTIDAD
            case 4:// ENTIDAD ESTADISTICA 1
                datos=new Object[Datos.getPilaEntidad().length][3];
                for(int x=0;x<Datos.getPilaEntidad().length;x++){
                    datos[x]=new Object[]{Datos.getPilaEntidad()[x].getBfiltro(),Datos.getPilaEntidad()[x].getCruc(),Datos.getPilaEntidad()[x].getCnombre()};
                }                
                columnas = new Object[]{"Filtro", "RUC", "ENTIDAD"};
                
                System.out.println(0);
                break;
            case 1:// PROVEEDOR
            case 5:// PROVEEDOR ESTADISTICA 1
                datos=new Object[Datos.getPilaProveedor().length][3];
                for(int x=0;x<Datos.getPilaProveedor().length;x++){
                    datos[x]=new Object[]{Datos.getPilaProveedor()[x].getBfiltro(),Datos.getPilaProveedor()[x].getCruc(),Datos.getPilaProveedor()[x].getCnombre()};
                }                
                columnas = new Object[]{"Filtro", "RUC", "PROVEEDOR"};
                System.out.println(1);
                break;
            case 2:// FORMALIZACION
                datos=new Object[Datos.getPilaFechas().length][3];
                for(int x=0;x<Datos.getPilaFechas().length;x++){
                    datos[x]=new Object[]{Datos.getPilaFechas()[x].getBfiltro(),Datos.getPilaFechas()[x].getCfecha()};
                }                
                columnas = new Object[]{"Filtro", "FECHA"};
                System.out.println(2);
                break;
            case 3:// ACUERDO
                datos=new Object[Datos.getPilaAcuerdoMarco().length][3];
                for(int x=0;x<Datos.getPilaAcuerdoMarco().length;x++){
                    datos[x]=new Object[]{Datos.getPilaAcuerdoMarco()[x].getBfiltro(),Datos.getPilaAcuerdoMarco()[x].getCacuerdo()};
                }                
                columnas = new Object[]{"Filtro", "ACUERDO M."};
                System.out.println(3);
                break;           
            default:break;
        }
                
        tblObjeto.setModel(new javax.swing.table.DefaultTableModel(datos,columnas) {
            Class[] types = new Class [] {
                Boolean.class, String.class, String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        if (tblObjeto.getColumnModel().getColumnCount() > 0) {
            tblObjeto.getColumnModel().getColumn(0).setMaxWidth(50);
            tblObjeto.getColumnModel().getColumn(1).setMaxWidth(200);
        }
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFiltro().setVisible(true);
                System.out.println("INICIO");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFiltro;
    private javax.swing.JCheckBox chkTodo;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblObjeto;
    // End of variables declaration//GEN-END:variables
}
